version: '3.4'


services:
  catalogdb:
    image: mongo
  basketdb:
     image: redis:alpine
  discountdb:
     image: postgres
  pgadmin:
     image: dpage/pgadmin4
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
        context: .
        dockerfile: Services/Catalog/Catalog.API/Dockerfile
 
    ports:
       - "8000:8080"

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    ports:
       - "8001:8080"
  portainer:
    image: portainer/portainer-ce
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

volumes:
    mongo_data: 
    portainer_data:
    postgres_data:
    pgadmin_data:

